version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

  [[analyzers]]
name = "test-coverage"
enabled = true

# .deepsource.toml

[analysis]
  [analysis.python]
    [analysis.python.bandit]
      enabled = true  # Enable Bandit security analysis

